### ISSUE TITLE
doesnt work in version 23.10.07.0

### ISSUE THREAD

**Issue by kingofcube** [TheMushrunt/Sonic-3-AIR-with-Extra-Mushrooms#10]
I tested it in 23.10.07.0 and UH
it didn't work

**Comment by TheMushrunt** [comment]
no idea what you're talking about. there's a newer test build than that anyways so this means nothing to me. if you're gonna use those you're gonna need to keep up

**Comment by kingofcube** [comment]
> no idea what you're talking about. there's a newer test build than that anyways so this means nothing to me. if you're gonna use those you're gonna need to keep up

23.10.07.0 is literally the only test build to include an android version :/

**Comment by TheMushrunt** [comment]
> > no idea what you're talking about. there's a newer test build than that anyways so this means nothing to me. if you're gonna use those you're gonna need to keep up
> 
> 23.10.07.0 is literally the only test build to include an android version :/

okay then at least tell me what's wrong with the mod instead of saying "UH it doesnt work".
it works in stable builds, and it works in the test builds i've used.

**Comment by kingofcube** [comment]
> > > no idea what you're talking about. there's a newer test build than that anyways so this means nothing to me. if you're gonna use those you're gonna need to keep up
> > 
> > 
> > 23.10.07.0 is literally the only test build to include an android version :/
> 
> okay then at least tell me what's wrong with the mod instead of saying "UH it doesnt work". it works in stable builds, and it works in the test builds i've used.

idk it just doesn't work
I can give u my mod list on discord if u want
