### ISSUE TITLE
This mod does not comply with Sonic 3 AIR's open source license

### ISSUE THREAD

**Issue by ShadowXeldron** [TheMushrunt/Sonic-3-AIR-with-Extra-Mushrooms#2]
As per the license that Sonic 3 AIR uses - the [GNU General Public License](https://github.com/Eukaryot/sonic3air/blob/main/LICENSE) - all modifications have to be shared under the exact same license. Since this mod explicitly uses modified code from base S3AIR, it is also covered by the GPL. However, not only is this repository not licensed under the GPL, it also contains this particular line in the README.md:

"...do not release modifications of them without my permission." (this was paraphrased to the line in question)

These are both in breach of part C of [section 5 of the GNU GPL](https://github.com/Eukaryot/sonic3air/blob/dba0870f77960921a5773c09441c1d44a23ebc07/LICENSE#L208), which reads:

    c) You must license the entire work, as a whole, under this
    License to anyone who comes into possession of a copy.  This
    License will therefore apply, along with any applicable section 7
    additional terms, to the whole of the work, and all its parts,
    regardless of how they are packaged.  This License gives no
    permission to license the work in any other way, but it does not
    invalidate such permission if you have separately received it.

There are two ways to avoid this issue:

1. Relicense the mod to the GNU General Public License and remove the offending line from the readme (absolutely the best way to go - note that this **will** mean others can use your code without permission as long as they share their modifications under the exact same license)

Alternatively,

2. Receive explicit permission from [all contributors on the project](https://github.com/Eukaryot/sonic3air/graphs/contributors) (This might be a faff; I probably wouldn't do this unless you really don't want to go the GPL route)

I don't really know a better way to report this, so I'm opening an issue in order to bring this to your attention.

**Comment by TheMushrunt** [comment]
if i'm being honest i really don't wanna do either option but i'll probably just get rid of that line in the README since it's less of a hassle. i just _really_ don't like the idea of people, say, taking parts of the code, leaving it unmodified, and turning it into a standalone mod because it goes against the point of me making the mod in the first place
