### ISSUE TITLE
Can't beat LRZ act 1 with ESA and Special Rings won't load

### ISSUE THREAD

**Issue by Emmmmmm12** [TheMushrunt/Sonic-3-AIR-with-Extra-Mushrooms#4]
You can't beat act 1 of LRZ (the stage is going to lock in the mini boss area, load the act2 palette and you're stuck there forever) Special Rings won't load neither.

**Comment by TheMushrunt** [comment]
are you ABSOLUTELY sure my mod is causing this? i have not encountered anything like this within my own experience and none of the code even alters Lava Reef Zone's scripts or Special Stage Rings.

**Comment by Emmmmmm12** [comment]
Yes, it happens with all of the extra characters tho, the base game characters are fine.
The only way I found to fix it is to put the mod below extra characters unlimited.

**Comment by TheMushrunt** [comment]
that is _extremely_ unusual, the game has worked fine for me and i have Extra Mushrooms above it. would you like to get in closer contact with me so we could troubleshoot this?

**Comment by Emmmmmm12** [comment]
I just found out why
There's a mod called Triple Trouble 16-bit Effects that is causing this for some reason.
You can close this then, it's a mod conflict. Sorry for the trouble

**Comment by TheMushrunt** [comment]
i haven’t used that mod, mainly because i’m not invested in effects like that. thanks for informing me of that though. i’ll close the issue now that you found the proper cause
