### ISSUE TITLE
EM level select bugs - special stages are always Sonic/Tails, competition stages are always Sonic

### ISSUE THREAD

**Issue by TimerBunneh** [TheMushrunt/Sonic-3-AIR-with-Extra-Mushrooms#5]
It seems that unless the base level select is enabled, special stages will always be played as Sonic and Tails no matter which character is chosen, and competition levels will always be Sonic. I have tested this with various mods enabled as well as with Extra Mushrooms being the only mod enabled.

This does not appear to affect main zones or bonus stages. I am using version 2.3.5 and the following settings (Special Stages are set to S3/S&K):
![image](https://github.com/TheMushrunt/Sonic-3-AIR-with-Extra-Mushrooms/assets/59062598/107612cd-e4fe-4167-aebe-296ab3e56d36)

**Comment by TheMushrunt** [comment]
i actually had no idea about this issue because i constantly just use Sonic & Tails whenever i test things. thank you very much for informing me of this Timer, i'll see what i can do to correct this issue

**Comment by TheMushrunt** [comment]
i committed fixes for it, please let me know if there's any further issues. until then, i'm closing it here.
