### ISSUE TITLE
Sonic 3 A.I.R Extra Mushroom V2.3.5 glitch with blue spheres from level select

### ISSUE THREAD

**Issue by Isaac-Son** [TheMushrunt/Sonic-3-AIR-with-Extra-Mushrooms#6]
Hi, so I just encountered a weird bug on blue spheres from level select. Whenever the "Use Base Level Select" is not enable, blue spheres will always make me play as Sonic & Tails for every playable character in level select. I forgot to show up Knuckles & Tails but it's the same thing for them too. Here's the video.

https://youtu.be/9gjqfFz7238

Edit : Just saw someone else mentioning the issue here. I'm new to this I didn't know they were closed issue here.

**Comment by TheMushrunt** [comment]
yeah i fixed this in recent commits.
