### ISSUE TITLE
Audio Overhaul support?

### ISSUE THREAD

**Issue by TimerBunneh** [TheMushrunt/Sonic-3-AIR-with-Extra-Mushrooms#7]
I know you said that you wouldn't add support for mods unless you liked them or were really popular, but I think this one is popular enough to warrant it--plus there are parts where it clashes with Extra Mushrooms.

[Audio Overhaul](https://gamebanana.com/mods/448675)is a large audio mod that recently added custom main menu themes. However, this clashes with Extra Mushrooms due to the use of the same function, MainMenuBG.Run(). I managed to fix this by copying Audio Overhaul's BGM code into Extra Mushrooms and it works fine, but official support would be nice.

Additionally, there is an option for a custom title screen, and enabling it overrides any of Extra Mushrooms' customizations. A small things, but nonetheless something to report.

That's all I have to report. If you choose not to add it, I won't complain. (I tried to convince the author to use base. commands...)

**Comment by TheMushrunt** [comment]
i've never used the mod, and honestly i don't see a point in using it since it's a mod i don't really like, since **i prefer to only use Genesis music for a Genesis game.**

**Comment by TheMushrunt** [comment]
actually i'm reopening this to fucking mention that i've noticed a portion of the Pause Sound scripts (pretty much all of them, actually) taken directly from Extra Mushrooms which is absolutely unacceptable from the Audio Overhaul dev(s).
https://cdn.discordapp.com/attachments/708852212922712118/1135207047709851768/image.png
