### ISSUE TITLE
Origins Hyper Palette flashing

### ISSUE THREAD

**Issue by SirForte** [TheMushrunt/Sonic-3-AIR-with-Extra-Mushrooms#8]
The Origins Hyper Palette flashing doesn't actually account for all instances of hyper sonic's palette
In gameplay, it works fine, but it doesn't work on the ending pose sprites.

**Comment by TheMushrunt** [comment]
i'm pretty sure the function for the ending pose hasn't been put into a stable release yet so i have no reason to add it into Extra Mushrooms yet. i'll keep the issue open though as a reminder for when a new stable release is made

**Comment by TheMushrunt** [comment]
i've pushed a commit that adds in the endpose hyper flashing, it'll be in the next update when i'm done doing whatever i have left that i'd like to put in.
