### ISSUE TITLE
New ESU version replaces (almost) all ES character icons with Knuckles

### ISSUE THREAD

**Issue by TimerBunneh** [TheMushrunt/Sonic-3-AIR-with-Extra-Mushrooms#9]
The Sonic Hacking Contest opened up today, and it seems the new version of Extra Slots Unlimited that was released is not quite compatible with Extra Mushrooms' level select, in that it replaces all character icons (except for Mighty, Ray, and Amy, which work fine--at least with their new versions) with Knuckles' icon. It's a strange one, and I figured you should know about it.

Other than that, there seem to be no other issues regarding the new ESU version.

**Comment by TheMushrunt** [comment]
this is probably because there’s changes made to how level select is done with ESU. will be fixed when i have time

**Comment by TheMushrunt** [comment]
i was correct, in a way? the ESU update got rid of a function i made use of, which was why it defaulted to Knuckles i guess. i've made a commit to Extra Mushrooms that fixes this hopefully

**Comment by TimerBunneh** [comment]
I can confirm that this is indeed fixed. Much obliged
